databases:
  - name: pages_projectdb
    plan: free
    databaseName:
    user: pages_project

services:
  - type: web
    plan: free
    name: pages_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pages_project.asgi:application -k uvicorn.workers.UvicornWorker"
